data:
    batch_size: 64
    data_dir: ~/research/data/pytorch
    dataset: cifar10
    num_workers: 1
    seed: 100
    shape: [ 3, 32, 32 ]
    shuffle: true
    val_split: 0
model:
    class: MDAE
    training:
        grad_clip: 0.0
        optimizer:
            class: adam
            config:
                betas:
                    - 0.9
                    - 0.999
                eps: 1.0e-08
                lr: 1.0e-04
                weight_decay: 0.0
        seed: 1685
        sampling:
            nrow: 10
            ncol: 10
            mode: "underdamped"
            eps_scale: 0.5
            friction: 0.5
            lipschitz: 1.0
            steps: 10
        sync_log: false
    M: [ 8 ]
    dataset: ${data.dataset}
    phi:
        class: U2NetCifarWide
        config:
            in_channels: ???
            out_channels: ???
            factor: 2
            bias: true
    input_shape: ${data.shape}
    sigma: [ 1.0 ]
    sigmoid: true
trainer:
    acc:
    auto: true
    dir: ./logs/
    epochs: 1000
    gpus: 4
    grad_acc: 1
    limit_train: 1.0
    limit_val: 1.0
    load: null
    log_freq: 50
    name: mdae_cifar10
    neptune:
    precision: 32
    resume: null
    test: false
